name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Installer requirements.txt
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Créer fichier .env
        run: |
          echo "DB_HOST=mysql" >> .env
          echo "DB_PORT=3306" >> .env
          echo "DB_NAME=labo03_db" >> .env
          echo "DB_USER=labo03" >> .env
          echo "DB_PASS=lab03" >> .env
          echo "REDIS_HOST=redis" >> .env
          echo "REDIS_PORT=6379" >> .env
          echo "REDIS_DB=0" >> .env

      - name: Run tests
        working-directory: src
        run: python -m pytest -v



     # - name: Set up Python
      #  uses: actions/setup-python@v4
       # with:
        #  python-version: '3.11'
      #- name: Install dependencies
       # run: |
       #   python -m pip install --upgrade pip
        #  pip install -r requirements.txt

      #- name: Run tests
       # working-directory: src
       # run: |
        #  python3 -m pytest
