name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Créer fichier .env
        run: |
          echo "DB_HOST=mysql" >> .env
          echo "DB_PORT=3306" >> .env
          echo "DB_NAME=labo03_db" >> .env
          echo "DB_USER=labo03" >> .env
          echo "DB_PASS=lab03" >> .env
          echo "REDIS_HOST=redis" >> .env
          echo "REDIS_PORT=6379" >> .env
          echo "REDIS_DB=0" >> .env

      - name: Build Docker images
          run: docker compose build

      - name: Start services
        run: docker compose up -d

      - name: Wait for services to be ready
        run: |
          echo "Waiting for services to start..."
          sleep 10
          # Optionnel : vérifier qu'un service spécifique est prêt
          # docker compose exec -T store_manager python -c "import time; time.sleep(5)"
      - name: Run tests
        working-directory: src
          run: docker compose exec -T store_manager python -m pytest



     # - name: Set up Python
      #  uses: actions/setup-python@v4
       # with:
        #  python-version: '3.11'
      #- name: Install dependencies
       # run: |
       #   python -m pip install --upgrade pip
        #  pip install -r requirements.txt

      #- name: Run tests
       # working-directory: src
       # run: |
        #  python3 -m pytest
